Vagrant.configure("2") do |config|

  config.vm.define :servidor1 do |servidor1|
    d1 = ".vagrant/disco1.vdi"
    d2 = ".vagrant/disco2.vdi"
    d3 = ".vagrant/disco3.vdi"
    servidor1.vm.box = "debian/buster64"
    servidor1.vm.hostname = "Servidor1"

    #servidor1.vm.network :public_network,:bridge=>"enp2s0"
    servidor1.vm.network :public_network,:bridge=>"wlp1s0"
    servidor1.vm.network :private_network, ip: "192.168.100.1", virtualbox__intnet:"mired1"

    servidor1.vm.provider :virtualbox do |v|
	    if not File.exist?(d1)
	    	v.customize ["createhd", "--filename", d1, "--size", 1 *  1024]
	    end
	    v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 1,"--device", 0, "--type", "hdd", "--medium", d1]

	    if not File.exist?(d2)
	    	v.customize ["createhd", "--filename", d2, "--size", 1 * 1024]
	    end
	    v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 2,"--device", 0, "--type", "hdd", "--medium", d2]

      if not File.exist?(d3)
        v.customize ["createhd", "--filename", d3, "--size", 1 * 1024]
      end
      v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 3,"--device", 0, "--type", "hdd", "--medium", d3]
    end
  end

  config.vm.define :cliente1 do |cliente1|
    cliente1.vm.box = "debian/buster64"
    cliente1.vm.hostname = "Cliente1"
    #cliente1.vm.network :public_network,:bridge=>"enp2s0"
    cliente1.vm.network :public_network,:bridge=>"wlp1s0"
    cliente1.vm.network :private_network, ip: "192.168.100.2", virtualbox__intnet:"mired1"
  end

#  config.vm.define :cliente2 do |cliente2|
#    cliente2.vm.box = "mwrock/Windows2016"
#    cliente2.vm.hostname = "Cliente1"
#    cliente2.vm.network :public_network,:bridge=>"enp2s0"
    #cliente2.vm.network :public_network,:bridge=>"wlp2s0"
#    cliente2.vm.network :private_network, ip: "192.168.100.3", virtualbox__intnet:"mired1"
#  end

end
